[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[variables]
PYTHONPATH = '/app:/app/src'

[start]
cmd = 'python main.py'