[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.poetry', 'ffmpeg']

[phases.install]
cmds = [
  'poetry install --no-interaction --no-ansi'
]

[variables]
PYTHONPATH = '/app:/app/src'
PYTHON_VERSION = '3.11'

[start]
cmd = 'python3 start.py'
