name: CI

permissions:
  contents: read
  pull-requests: write  # For coverage reports and comments

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'     # All feature branches (type/issue-number-description)
      - 'fix/**'         # All fix branches
      - 'hotfix/**'      # All hotfix branches
      - 'release/**'     # All release branches
    paths-ignore:
      - '**.md'          # Documentation files
      - 'docs/**'        # Documentation directory
      - '.github/ISSUE_TEMPLATE/**'  # Issue templates
      - '.github/PULL_REQUEST_TEMPLATE.md'  # PR template
      - 'LICENSE'        # License file
      - '.gitignore'     # Git ignore file
  pull_request:
    branches:
      - main
      - develop
      - 'feature/phase*' # Phase integration branches
      - 'release/**'     # Release branches
    paths-ignore:
      - '**.md'          # Documentation files
      - 'docs/**'        # Documentation directory
      - '.github/ISSUE_TEMPLATE/**'  # Issue templates
      - '.github/PULL_REQUEST_TEMPLATE.md'  # PR template
      - 'LICENSE'        # License file
      - '.gitignore'     # Git ignore file

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python and Poetry
      uses: ./.github/actions/setup-python-poetry
      with:
        python-version: "3.11"
        cache-key-suffix: "-lint"

    - name: Run code formatting check (Black)
      run: poetry run black --check src/ tests/

    - name: Run import sorting check (isort)
      run: poetry run isort --check-only src/ tests/

    - name: Run linting (flake8)
      run: poetry run flake8 src/ tests/

    - name: Run type checking (mypy)
      run: poetry run mypy src/ --ignore-missing-imports

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
      fail-fast: false  # Continue other jobs if one fails

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry with retry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
      env:
        # Increase timeout for Poetry installation
        POETRY_HTTP_TIMEOUT: 300

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ matrix.python-version }}-

    - name: Install dependencies with retry
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: |
        # Retry logic for Poetry install
        for i in {1..3}; do
          if poetry install --no-interaction --no-root; then
            echo "Poetry install succeeded on attempt $i"
            break
          else
            echo "Poetry install failed on attempt $i"
            if [ $i -eq 3 ]; then
              echo "Poetry install failed after 3 attempts"
              exit 1
            fi
            sleep 30
          fi
        done
      env:
        POETRY_HTTP_TIMEOUT: 300
        POETRY_REQUESTS_TIMEOUT: 300

    - name: Install project
      run: poetry install --no-interaction

    - name: Set up test environment
      run: |
        mkdir -p data logs
        cp .env.example .env.test
        echo "DISCORD_TOKEN=MTA1234567890123456.GH7890.abcdefghijklmnop123456789012345678901234" >> .env.test
        echo "OPENAI_API_KEY=sk-abcdef1234567890abcdef1234567890abcdef1234567890ab" >> .env.test
        echo "LOG_LEVEL=DEBUG" >> .env.test

    - name: Run tests with pytest
      env:
        DISCORD_TOKEN: MTA1234567890123456.GH7890.abcdefghijklmnop123456789012345678901234
        OPENAI_API_KEY: sk-abcdef1234567890abcdef1234567890abcdef1234567890ab
        LOG_LEVEL: DEBUG
      run: |
        poetry run pytest tests/ \
          --forked \
          --tb=short \
          --cov=src \
          --cov-report=xml \
          --cov-report=html \
          --cov-report=term-missing \
          --junit-xml=test-results-${{ matrix.python-version }}.xml \
          -m "not slow and not network" \
          --timeout=60 \
          --timeout-method=thread \
          --maxfail=5 \
          -n auto \
          -v

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          test-results-${{ matrix.python-version }}.xml
          htmlcov/
          .coverage

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
      env:
        POETRY_HTTP_TIMEOUT: 300

    - name: Install dependencies
      run: poetry install --no-interaction
      env:
        POETRY_HTTP_TIMEOUT: 300

    - name: Run security checks (bandit)
      run: |
        poetry add --group dev bandit[toml]
        poetry run bandit -r src/ -f json -o bandit-report.json || true

    - name: Run dependency vulnerability check (safety)
      run: |
        poetry add --group dev safety
        poetry self add poetry-plugin-export
        poetry export -f requirements.txt --output requirements.txt --without-hashes
        poetry run safety check -r requirements.txt --json --output safety-report.json || true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

  docker-integration-test:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 15
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: nescordbot:ci-test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create test environment
      run: |
        # Create test environment file for Docker
        echo "DISCORD_TOKEN=MTA1234567890123456.GH7890.abcdefghijklmnop123456789012345678901234" > .env.docker
        echo "OPENAI_API_KEY=sk-abcdef1234567890abcdef1234567890abcdef1234567890ab" >> .env.docker
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env.docker
        echo "LOG_LEVEL=DEBUG" >> .env.docker

    - name: Run integration tests in Docker
      run: |
        # Run pytest with integration marker inside Docker container
        docker run --rm \
          --env-file .env.docker \
          -v "$(pwd)/test-results:/app/test-results" \
          nescordbot:ci-test \
          bash -c "
            poetry run pytest tests/ \
              --verbose \
              -m 'integration' \
              --maxfail=3 \
              --timeout=120 \
              --junit-xml=/app/test-results/docker-integration-results.xml || true
          "

    - name: Test bot startup and environment validation
      run: |
        # Test that the bot can be imported and basic validation works
        docker run --rm \
          --env-file .env.docker \
          nescordbot:ci-test \
          sh -c "poetry run python -c 'from nescordbot.main import BotRunner; runner = BotRunner(); runner.setup_logging(); print(\"✅ Bot runner can be initialized in Docker\"); result = runner.validate_environment(); print(f\"✅ Environment validation in Docker: {result}\")'"

    - name: Verify Poetry script functionality
      run: |
        # Test that Poetry start script works correctly
        docker run --rm \
          --env-file .env.docker \
          nescordbot:ci-test \
          poetry run start --help || echo "✅ Start script is configured and accessible"

    - name: Test Docker container health
      run: |
        # Test the health check functionality
        docker run --rm \
          --env-file .env.docker \
          nescordbot:ci-test \
          poetry run python -c "from nescordbot.__main__ import main; print('✅ Docker container health check passed')"

    - name: Upload Docker integration test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-integration-test-results
        path: |
          test-results/docker-integration-results.xml
